### ISSUE TITLE
Need document for connect database 

### ISSUE THREAD

**Issue by khanh19934** [crookse/deno-drash#75]
Do you have any plan for document to connect the database such as mongodb, mysql etc .. ?
I try some lib of deno to connect mysql such as `deno_mysql` but i dont know how to use in resource. Like we can pass the `client` as argument of class resource ?

**Comment by crookse** [comment]
Hi @khanh19934,

You can do this by adding a global member: https://crookse.github.io/deno-drash/#/tutorials/adding-global-members

I know it might not be too intuitive because adding the class/service that handles your MySQL processes will be added to the `Drash.Members` namespace, but it’ll work.

I’ll look into adding configurations to the server for MySQL connections though. I’m also open to suggestions if you have any.

**Comment by crookse** [comment]
Hey @khanh19934 ,

Here's a solution for you:

```typescript
// File: client.ts

import { Client } from "https://deno.land/x/mysql/mod.ts";

const client = await new Client().connect({
  hostname: "127.0.0.1",
  username: "root",
  db: "deno_mysql",
});

export default client;
```

```typescript
// File: home_resource.ts

import Drash from "https://deno.land/x/drash@v0.27.3/mod.ts";
import client from "./client.ts";

export default class HomeResource extends Drash.Http.Resource {

  static paths = ["/"];

  public async GET() {
    this.response.body = await client.query(`select * from user`);
    return this.response;
  }
}
```

```typescript
// File: app.ts

import Drash from "https://deno.land/x/drash@v0.27.3/mod.ts";

import HomeResource from "./home_resource.ts";

let server = new Drash.Http.Server({
  address: "localhost:1337",
  response_output: "application/json",
  resources: [HomeResource]
});

server.run();
```

```
deno --allow-net --allow-write app.ts
```

You'll want to make `client.ts` fit your MySQL requirements.

Below is a picture of it working. As you can see, I started up my server and ran `curl localhost:1337`. I got back the data from my `user` table. The left side of the screen is my project filesystem. The right side is my MySQL table, my server being run, and the `curl` request.

<img width="1680" alt="Screen Shot 2019-12-27 at 21 17 31" src="https://user-images.githubusercontent.com/12766301/71537741-76e0e880-28ee-11ea-8c0e-5bc943ab9eaf.png">

**Comment by crookse** [comment]
@khanh19934,

I made a documentation page related to this issue: https://crookse.github.io/deno-drash/#/third-party-tutorials/databases/deno-mysql
